### ISSUE TITLE
Does this API expose the LED and Nightlight functions?

### ISSUE THREAD

**Issue by QandnotU** [bbernstein/eero-js-api#1]
Attempting to cobble together a HomeKit plugin through HomeBridge using this API. Something that simple that would allow me to expose the LED and Nightlight as an accessory in HomeKit so I can turn these lights on/off through automations. Do you know if these functions are exposed on the API?

**Comment by bbernstein** [comment]
It appears this is exposed through the API. When calling the the eeros api, it returns (among many other things):

```
led_action: '/2.2/eeros/<ID>/led'
nightlight: null
led_on: true
```

I don't see an action for nightlight, but maybe the models I have don't include them.
I don't have much time to work on this, but if you feel like contributing, please let me know.

Thanks,

Bernie
